### PR TITLE
Truncate message at 10KB

### PR DESCRIPTION
**Pull request by heldersepu**
This fixes Issue #308

### CODE REVIEW

**Comment by heldersepu** [comment]
> This is a good catch, though I have never encountered such a huge commit message in my life!

Ye, first-time I've seen it too! Seem Github Enterprise when merging branches the default message is a concatenation of all commits (user still has the option to overwrite)...

looking into that test

**Comment by heldersepu** [comment]
@YoussB Can you check why is the CI failing ...

**Comment by aoldershaw** [comment]
@heldersepu looks like this line is failing on alpine: https://github.com/concourse/git-resource/pull/309/files#diff-daaa154e22be44798ffcddf12a70e03eR121

```sh
local message=$(shuf -zer -n20000  {A..Z})
```

You should be able to achieve something similar with:

```sh
local message=$(cat /dev/urandom | tr -dc A-Z | head -c 20000 ; echo '')
```

Source: https://unix.stackexchange.com/a/230676

**Comment by heldersepu** [comment]
> @heldersepu looks like this line is failing on alpine: https://github.com/concourse/git-resource/pull/309/files#diff-daaa154e22be44798ffcddf12a70e03eR121
> 
> ```shell
> local message=$(shuf -zer -n20000  {A..Z})
> ```
> 
> You should be able to achieve something similar with:
> 
> ```shell
> local message=$(cat /dev/urandom | tr -dc A-Z | head -c 20000 ; echo '')
> ```
> 
> Source: https://unix.stackexchange.com/a/230676

@aoldershaw Done, I think we are good to go...

**Pull request merged**
