### PR TITLE
decrypt git-crypt repositories automatically

### PR DESCRIPTION
**Pull request by dmrschmidt**
implementation for #7 

all info in the README

### CODE REVIEW

**Comment by simonjohansson** [comment]
Ping.

**Comment by jtarchie** [comment]
We are unfamiliar with this workflow. Can someone provide us an example pipeline, description of workflow to test this out?

**Comment by jgrau** [comment]
I am no expert, in fact I'm only just starting to use git-crypt on my own repo but this is the workflow I would use for testing git-crypt.

1. locally install `git-crypt`. See https://github.com/AGWA/git-crypt/blob/master/INSTALL.md
2. In a git repo `git-crypt init`
3. Mark a file for encryption by creating a `.gitattributes` with the content

```
credentials.yml filter=git-crypt diff=git-crypt
```

This will encrypt the file `credentials.yml` when that is later committed.

4. Add and commit the `.gitattributes`
5. Create the `credentials.yml` and `add` and `commit` it.
6. Publish the branch to github and note that the content of `credentials.yml` is encrypted.
7. In order for your collaborators (and concourse) to decrypt the encrypted files, create an unlocking key: `git-crypt export-key my-key.key`


In another directory (imagining being on another devs machine or in a concourse git resource container) you could clone the repo. The `credentials.yml` is still encrypted but you have received the `my-key.key` file and you put it in the cloned repo. You can then

8. run `git-crypt unlock my-key.key` and the `credentials.yml` is now decrypted.

**Comment by jgrau** [comment]
Reading the sourcecode for this PR you base64 encode the exported key which `git-resource` uses to unlock the git repo.

**Comment by dmrschmidt** [comment]
@jgrau's description is exactly our flow. The base64 encoded key for the resource setting can be obtained via `git-crypt export-key -- - | base64`.

**Comment by vito** [comment]
looks good, thanks!

**Comment by jgrau** [comment]
This is awesome. Thanks!

**Pull request merged**
