### PR TITLE
Install git lfs in resource image

### PR DESCRIPTION
**Pull request by cjcjameson**
- This will add ~3 MB to the image, we estimate

### CODE REVIEW

**Comment by vito** [comment]
What's the externally visible delta? It'll now fetch your files for you on `pull` or something/

**Comment by cjcjameson** [comment]
No external-facing delta for a repo that has no files tracked with git-lfs
The external-facing delta for a repo that does have files under git-lfs is that:
- Without git-lfs installed, a `git pull` gets you a pointer to the file
- With git-lfs installed, the large file pointer is smudged into an actual copy of the file at `fetch` time

Additional console output would provide evidence of the latter case happening. Pushing will also show a similar difference.

We don't think trying to push into lfs without lfs installed would be a reasonable workflow

**Comment by vito** [comment]
Cool, sounds good to me. Will have a look after 0.71.0 (trying to not introduce more deltas for that one as we haven't released in a while). Thanks!

**Comment by vito** [comment]
Just remembered this - will merge it in now. Thanks!

**Pull request merged**
