### PR TITLE
Add param disable_git_lfs to assets/in

### PR DESCRIPTION
**Pull request by SHyx0rmZ**
This adds a new param called `use_lfs` to `assets/in`, which can be used to `get` repositories without also checking out data from Git LFS.

### CODE REVIEW

**Comment by SHyx0rmZ** [comment]
Fixes #79.

**Comment by philk** [comment]
Hah, I have a branch that's identical to this that I've been testing locally except I named the parameter `disable_git_lfs`. 👍

**Comment by SHyx0rmZ** [comment]
Hm, inverting the logic didn't occur to me when I added this to fix our pipeline. I think I like `disable_git_lfs` more, because it should also simplify the `jq` filter. Will change it tomorrow.

**Comment by vito** [comment]
Change looks good, but I'd like to understand why you need this before adding another knob. :) Is it similar to the reason for skipping submodules? (i.e. optimization)

**Comment by philk** [comment]
We have around 2GB of files in git-lfs that we don't need for tests, just dev so it's to avoid pulling those down in CI.

**Comment by SHyx0rmZ** [comment]
Similiar situation here. We have a pipeline that tests all commits to the configuration management repository. Not fetching from Git LFS (unless required) saves us lots of traffic and (more importantly) build time.

**Comment by vito** [comment]
Sounds reasonable. Thanks!

**Pull request merged**
