### PR TITLE
libressl fixes and latest git lfs

### PR DESCRIPTION
**Pull request by alucillo**
1. Addresses an issue I encountered when building locally as a result of libressl
2. Upgrades git lfs to the latest version

### CODE REVIEW

**Comment by horjulf** [comment]
Since `git` already comes from alpine, is there any issue nowadays installing `git-lfs` from alpine ?

**Comment by vito** [comment]
Neat! Yeah, it looks like there's a `git-lfs` package we can use now.

**Comment by suda** [comment]
I believe this PR might be the thing that fixes #202 failing to build.

**Comment by alucillo** [comment]
Take a look.  I updated the PR to install git-lfs via apk now.

**Comment by vito** [comment]
@alucillo Perfect, thanks!

**Pull request merged**
